
package ru.otus.jaxws.calculator;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoapCalculator", targetNamespace = "http://jaxws.otus.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapCalculator {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addNumbers", targetNamespace = "http://jaxws.otus.ru/", className = "ru.otus.jaxws.calculator.AddNumbers")
    @ResponseWrapper(localName = "addNumbersResponse", targetNamespace = "http://jaxws.otus.ru/", className = "ru.otus.jaxws.calculator.AddNumbersResponse")
    @Action(input = "http://jaxws.otus.ru/SoapCalculator/addNumbersRequest", output = "http://jaxws.otus.ru/SoapCalculator/addNumbersResponse")
    public int addNumbers(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
